### PR TITLE
Add Launch Settings

### PR DESCRIPTION
**Pull request by HurricanKai**
This adds a launchSettings.json file to every Project.
That way it should be easier to do configuration for people opening this Project up for the first Time.

There are different Profilers in the Maze Project for every (sensible) combination. Including Prims, see #5 (I hope I missed no other project that has different configurations). Also considering renaming Maze "Default" to "Random Walk"'

Every IDE should be able to recognize these Files.

I completly understand if this PR is rejected, this does clutter the Project View & Repo a bit.

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
I'm still fairly new to Visual Studio Code, so the launch settings look promising (I wasn't aware of them till now), but I want to do a little more research to make sure I handle it in the best way that works in all IDEs/scenarios including from just the command line.

**Comment by HurricanKai** [comment]
For the CLI there is --launch-profile
I assumed everyone supports this, as it's the default way to configure ASP.Net (Core)

**Comment by HurricanKai** [comment]
^ I hope I did that merge correctly 😅 the Github editor is a bit iffy

**Comment by ZacharyPatten** [comment]
I'm closing this PR for now. I already added the `launch.json` entries a while back. Feel free to open another one if you still have sugguestions.

**Pull request closed without merging**
