### PR TITLE
Tdd

### PR DESCRIPTION
**Pull request by dernewt**
NOTE: do not merge this branch into main, I only picked that because GitHub doesn't let me propose creating a new branch on your side. See Below.

I spoke to you on discord (Emacs#8339), floated the idea of code with tests. This is a feeler pull request as I'm not sure if it's something you want to pursue and if so what form it should take.

Right now I think a separate long lived branch "tdd" could be an option. This is one project is implemented (and I added a solution filter). It actually isn't strictly TDD as it doesn't have 100% coverage. I'm still feeling out the best way to test console apps and also didn't want to get too abstraction crazy. Unit tests are represented along with arguably limited integration tests. I also did represent an end-to-end test via driving a console app process though overall the distinctions between them are blurred as I shoved it all in one project and not really using a test harness that has clear distinctions between test types.

I did notice you have a root projects folder, I ended up sticking the test in that same folder. Could be done differently.

Either way open to your thoughts.

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
Hello again. :) Thanks for the interest in contributing.

I created an `experimental-test-driven-development` branch. So feel free to open a PR to that branch instead.

As for the content of the PR, I'll give it a look as soon as I can. I'm still not convinced that test driven developement will work well for console games, but I'll be curious to see what you come up with.

**Comment by dernewt** [comment]
I went ahead and did a second project to just further refine the idea (tweaked the first project a little after getting the feel for it more).

I'm surprised how resistant to Functional/EndToEnd testing Console apps are in csharp. I started another project in here to try to help with that (if it goes anywhere I'll throw it on nuget). Still has some issues with Console.Clear and Console.ReadKey.

Even though I really want to make more progress with testing Console I figure I'll pull this out of draft status given the experimental branch you made and see if anyone takes interest.

**Comment by dernewt** [comment]
I did consider restructuring to abstract System.Console but I felt that went too far astray from the project's goals. Note I did move all Console interaction into a single class (HumanPlayer). That said I'll fully admit I quickly strayed away from "test driven development" so I regret the branch name. I'm not a true believer (TM) but do think tests (unit/functional/end-to-end) need to be introduced earlier in learning programming.  That said I'll admit I was quite surprised how poor the functional/end-to-end experience was when dealing with System.Console. I figured between SetIn/SetOut and Process.Start I could "drive" console apps (think selenium) but found Console.ReadKey and Console.Clear to be problematic. Note I did end up splitting it into a library and maybe could find a better way to fool it in the future.

You are correct to point out Rock Paper Scissors have no unit tests of value, at that point I got on a side crusade with getting Console funtional/end-to-end testing working better. I never went back to it but yes it deserves revesting. Yes, one aspect of testing is for the RandomPlayer (though nothing says his distribution should be even). A more obvious use case is just verify the interactions of the basic "moves" i.e. "rock beats scissors" etc. I'll definitely revisit it. It does highlight a larger point of the simpler exercises having not much to "test" which is fair given their scope.

Agree about OOP not needed for testing, but adding more readability/structure is one other tangent I went on. For instance IPlay (excluding the win/lose/draw properties which could better go into some sort of round abstraction) to prompt the reader into imaging other sorts of implementations, perhaps a different AI strategy, a GUI human player, even some form of remote human player. I liked the logical progression from guess a number from one Player now here to two types of players (ai/human). I'm sure there are different good ways to structure it though I like moving away from the static "function toolbox" nature of starting programs.

**Comment by ZacharyPatten** [comment]
@dernewt I'm planning on adding a unit testing project to the `main` branch. However, I don't plan on using it for the same purposes as this pull requests intends to achieve. I mainly want to use it for stuff like unit testing the `README.md`, the website pages, etc. Even so, since I am planning on adding a unit testing project to the `main` branch, I am going to close this pull request because I intend on deleting the `experimental-test-driven-development` branch for now to avoid any confusion.

We are now starting to more heavily use other branches (specifically the `console-monsters` branch), so I feel it is time I cleaned up the branches a bit.

**Pull request closed without merging**
