### PR TITLE
Duck Hunt

### PR DESCRIPTION
**Pull request by CorinHyndman**

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
Thank you for your interest in contributing a #17 new game. This looks great! :)

Do you have an opinion on what you believe the _"Weight"_ should be on the table in the root `README.md`?

We need to add some additional files (see the "New Game Contribution Checklist" on #17), but I can do that for you.

My main comment from a code review perspective is that I think we can optimize the code a bit. On large screen sizes the game seems to lag a bit. I have a few ideas on how we can easily optimize it. I will keep you updated if I make progress on this topic.

**Comment by CorinHyndman** [comment]
The _"Weight"_ I would say is on par with Tanks so maybe a 4?

**Comment by ZacharyPatten** [comment]
I see you added some optimizations. Thanks! I will review when I have time. :)

Also, ignore the GitHub action braking on your fork. I need to update my "Website Deploy" action to only run on my repo (and not on forks). Sorry!

**Comment by ZacharyPatten** [comment]
I have added the blazor port, and I made a few changes in hopes to prevent the game from crashing when the console window is resized.

I'm sure there is more improvement that could be done (especially in the blazor port), but everything seems functioning and pretty reliable. I feel like this pull request is ready to merge. :)

Thanks again for the great contribution!

Feel free to open up additional pull requests if you would like to update the game in the future.

**Pull request merged**
