### PR TITLE
Add Maze Generator using Prims to Maze Project

### PR DESCRIPTION
**Pull request by HurricanKai**
I thought this might be interesting to the project, It is rather complex in Code, but the Concept seemed simple enough.

### CODE REVIEW

**Comment by HurricanKai** [comment]
It does create these lines unfortunately, I'm having a look how to fix this (maybe I'll just shift the entire grid by one)
Else I feel like this creates much more connected and less linear mazes.
image

**Comment by ZacharyPatten** [comment]
Thanks for the interest in contributing. :) If you get it working well enough, I'll gladly merge it in.

I may make some changes after merging though:

1. Depending on how large it ends up being, I may put it into a separate project "Maze Prims" and list it underneath "Maze" in the README. But so far it looks like not much more code, so likely no need to do that.

image

2. One of the small goals I have is to not have any dependencies, but if we need a priority queue, I may give up on that goal and pull in my [Towel](https://github.com/ZacharyPatten/Towel) project as a dependency for the generic [Heap](https://github.com/ZacharyPatten/Towel/blob/master/Sources/Towel/DataStructures/Heap.cs) data structure.

**Comment by HurricanKai** [comment]
I could rewrite the code to re-sort the list after every loop, but I felt that it is easier to understand with a Priority Queue

**Comment by ZacharyPatten** [comment]
I agree, re-sorting is not the best compared to using a proper data structure (priority queue). What you have is fine, and you don't need to pull in Towel for the merge request if you don't want to. I can do that after it is merged in. Whatever is easier for you.

**Comment by HurricanKai** [comment]
I'll be happy to do that, wanted to have a closer look at Towel for some time now :)

**Comment by HurricanKai** [comment]
All working now:
image

**Comment by HurricanKai** [comment]
I added a (commented out) directive `UsePrims` for now

**Pull request merged**
