### PR TITLE
Dice Game

### PR DESCRIPTION
**Pull request by javithegreat35**
Hello, I have created a new game called "Dice Game" which has the player go up against a computer and they will each roll a dice 10 times and the player who gets the higher number 10 times wins the game.

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
Hello. Thanks for checking out the repo and contributing. :)

I will review this pull request as soon as I have time to do so.

**Comment by ZacharyPatten** [comment]
I made some changes:

- f0801a3badd6d6bd8a61344d20c2505366c06b75 moved the project into the `Projects` directory because that is where all the projects are
- f1ada2daeb79fa6b4e4035eb33aa3c7d62e0d7d4 I changed `Console.ReadKey()` to `Console.ReadKey(true)` because this hides the user input (for example if the user types the `A` key)
- f3b01e843af9e33c4dc215f9605cabc334523e43 added a description of the game that shows when the application is launched
- ff86f299bb374d49c372bb67f109d8d948659774
  - changed the turn order so that the Rival rolls the dice first as I felt it would add more anticipation because the player knows what they need to roll to win.
  - removed the `Thread.Sleep` because I don't think it is entirely necessary here
  - updated the output verbiage a bit
- 638994a51e8927117c15c043c2abb9f9a4547019 removed `class Program` so that the code is top-level statements because it is shorter
- 4a168b72bed9b0473dcc86330a566c3457880142 used string interpolation to simplify the code from
  `"The score is now - You : " + playerPoints + ". Rival : " + rivalPoints + "."` to
  `$"The score is now - You : {playerPoints}. Rival : {rivalPoints}."`
- cd9290b225d26561243dd1815f210df8c6112c1c moved the declaration of `rivalRandomNum` and `playerRandomNum` inside the loop rather than before because that is generally the preferred place to declare variables

And I made some additions:
- 43d9c5f2579e4a98745a79efc96a18e2ad730e1c added a blazor port of the game so that it will appear on the website and be playable online :)
- 7acfdffa801959faa0f8ba47a0c15f1ced63c564 added the necessary files so that `Dice Game` shows up as an option when using Visual Studio Code
- eb2dfacf49a89ae30d166f48721a0873465f95b9 added a GitHub Actions workflow for build validation
- c18112d274d5fba7b2f1fc8c1c9c58d371851d3a added `Dice Game` to `README.md` so it shows up on the home page of the GitHub repo and and added a `Projects\Dice Game\README.md`

**Comment by javithegreat35** [comment]
Thank you so much! This was my first time working on something from GitHub, thank you for assisting me!

Best Regards,
Javier

**Comment by ZacharyPatten** [comment]
Thanks @javithegreat35 for contributing a new game, and congratulations on your first pull request on GitHub!

If you want to show off your game, it will be playable at this link once the GitHub Actions complete: https://zacharypatten.github.io/dotnet-console-games/Dice%20Game

#17

**Comment by ZacharyPatten** [comment]
By the way, yours was the first game to be contributed (other contributors contributed to existing games). If you would like that to be mentioned anywhere let me know.

For example,

> contributors: @javithegreat35

in the `Notes` column of the table in the `README.md`.

**Comment by javithegreat35** [comment]
Hello,
Sorry for the late response. Yes, you could mention me anywhere you see fit! Again thank you for all your help!

**Pull request merged**
